name: build

on:
  pull_request:
  push:

jobs:
  xgo:
    strategy:
      matrix:
        go_version:
          - 1.15.x
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: ev0-translate-server
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          v: true
          x: false
          ldflags: -s -w
      - 
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build/